### ISSUE TITLE
Além da documentação em texto, podiam providenciar contratos OpenAPI

### ISSUE THREAD

**Issue by paulomorgado** [teamlyzer/api#3]
https://en.wikipedia.org/wiki/OpenAPI_Specification
https://github.com/OAI/OpenAPI-Specification
https://www.openapis.org/
https://swagger.io/

**Comment by ghost** [comment]
@paulomorgado Obrigado pelo feedback, faz todo o sentido. 

Vai ser adicionada às tarefas por fazer.

**Comment by ghost** [comment]
Nesta fase nao justifica o trabalho. A rever no futuro
