### ISSUE TITLE
Is the api still open?

### ISSUE THREAD

**Issue by DiogoRoloOS** [teamlyzer/api#4]
When I try to fetch any endpoint, such as the sampled `api/rating/67` i'm always getting unauthorized, even when providing my username and password.

So, is the api still open?

**Comment by ghost** [comment]
Hi @DiogoRoloOS ,

The API is open but only for a static IP, and the username and password are provided by us. 

Please send us an email if you are still interested and describing what is the use case for the API. 

Thank you

**Comment by waldyrious** [comment]
I've submitted #5 to make the usage requirements clearer.
